SELECT
  DIM_PLAYER_SEASON.PLAYER_ID,
  DIM_PLAYER_SEASON.SEASON,
  COUNT(*) AS ROW_COUNT
FROM {{ ref('dim_player_season') }} AS DIM_PLAYER_SEASON
GROUP BY
  DIM_PLAYER_SEASON.PLAYER_ID,
  DIM_PLAYER_SEASON.SEASON
HAVING COUNT(*) > 1